site_name: Test docs
site_description: 'A docs test'
site_author: 'Juuso Autiosalo'
docs_dir: docs/
repo_name: 'mhausenblas/mkdocs-template'
repo_url: 'https://github.com/mhausenblas/mkdocs-template'
nav:
    - Home: index.md
    - About: about.md
theme:
  name: 'material'
