site_name: Test docs
site_description: 'A docs test'
site_author: 'Juuso Autiosalo'
docs_dir: docs/
repo_name: 'juusoautiosalo/mkdocs-test'
repo_url: 'https://github.com/juusoautiosalo/mkdocs-test'
nav:
    - Home: index.md
    - About: about.md
theme:
  name: 'material'
